### ISSUE TITLE
The process is being "Killed"

### ISSUE THREAD

**Issue by NavidRajabi** [askforalfred/alfred#33] opened 2020-06-22 06:09 UTC
### Hi there,
After preprocessing, the process is being killed after a couple of warnings as follow:

warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")

Killed:   0%|▏                                                                                                              | 4/2628 [00:11<2:09:00,  2.95s/it]

Also, all the evaluations are being killed for both best_seen and best_unseen checkpoints:

{'tests_seen': 1533,
 'tests_unseen': 1529,
 'train': 21023,
 'valid_seen': 820,
 'valid_unseen': 821}
Loading:  best_checkpoints/best_unseen.pth
Killed
=============================================================

{'tests_seen': 1533,
 'tests_unseen': 1529,
 'train': 21023,
 'valid_seen': 820,
 'valid_unseen': 821}
Loading:  best_checkpoints/best_seen.pth
Killed

I was wondering somebody who've faced this issue could help. I've already installed all the dependencies as mentioned, as well as adding CUDA 10.0 for the project.

**Comment by NavidRajabi** [comment] 2020-06-22 06:15
Btw, during the extraction of the full dataset, the process is being killed as well and I'm really curious why is this happening!

**Comment by MohitShridhar** [comment] 2020-06-22 16:27
@NavidRajabi are you running out of RAM? Currently, the preprocess function holds all the JSONs in memory before writing the processed files to disk.

**Comment by NavidRajabi** [comment] 2020-06-22 16:31
@MohitShridhar, I don't think so, since I'm running the job on a cluster node. Is there anyway to fix that or do it in a different way?

**Comment by MohitShridhar** [comment] 2020-06-22 16:43
@NavidRajabi how much RAM does your cluster have? I can't think of any other reason than memory for the python process to be [killed](https://unix.stackexchange.com/questions/238886/what-could-be-the-reasons-for-shell-scripts-kill-itself). Have you checked the your [syslogs](https://www.digitalocean.com/community/questions/python-script-gets-killed)

**Comment by MohitShridhar** [comment] 2020-06-22 16:45
Btw, are you using docker? If so, have you looking into [Docker memory options](https://docs.docker.com/engine/reference/run/#user-memory-constraints)?

**Comment by NavidRajabi** [comment] 2020-06-22 16:50
@MohitShridhar I have to check the RAM size but I cannot use Docker on my cluster. I'm installing the dependencies individually. I'll check the syslog. 

Thanks for your response and suggestions!

**Comment by SouLeo** [comment] 2020-06-24 20:44
I have the same issue, and by using htop I've determined I'm running out of RAM. I have a total of 16GB. May I ask how much RAM was used in your training?
![killed](https://user-images.githubusercontent.com/5667409/85625785-32c66a80-b629-11ea-87d4-10a4f5b30e7d.png)
![ominousbossfightmusic](https://user-images.githubusercontent.com/5667409/85625789-34902e00-b629-11ea-91a8-52ec45bf0976.png)

**Comment by MohitShridhar** [comment] 2020-06-24 21:06
Hmm... 16GB should be sufficient. Maybe there is a memory leak somewhere. But I can't seem to reproduce this. If possible, could you try using a [memory profiler](https://medium.com/zendesk-engineering/hunting-for-memory-leaks-in-python-applications-6824d0518774) and report back?

**Comment by MohitShridhar** [comment] 2020-06-25 01:22
@NavidRajabi and @SouLeo thanks for pointing this out!

Turns out computing metrics over the entire train set was consuming too much memory, so I disabled it for [now](https://github.com/askforalfred/alfred/commit/849c3b6f64ab34ef11f3a801c7033c423255f68f#). Pull the latest master and try it out. At least the memory shouldn't grow like crazy.

**Comment by NavidRajabi** [comment] 2020-06-25 01:39
@MohitShridhar thanks for the update! Is it going to solve the issue of unzipping the full dataset and the evaluation process for results json generation as well? since the issue was not limited to the training process.

**Comment by MohitShridhar** [comment] 2020-06-25 02:06
@NavidRajabi unfortunately there is not a lot I can do about the size of the full dataset. 

But for evaluation, my local PC (20GB RAM) can easily handle 3-5 threads without any issues. 
![image](https://user-images.githubusercontent.com/6535354/85645137-b5612100-b64d-11ea-9c0f-df53fc796a30.png)

Can you try reducing the `--num_threads`?

**Comment by MohitShridhar** [comment] 2020-06-25 02:13
Oh wait, it looks your preprocess function is consuming too much memory.

**Comment by MohitShridhar** [comment] 2020-06-25 02:16
@NavidRajabi to clarify, is your [7z unzip](https://github.com/askforalfred/alfred/blob/master/data/download_data.sh#L27) getting killed? or the [preprocessing step](https://github.com/askforalfred/alfred/blob/master/data/preprocess.py#L43)?

**Comment by NavidRajabi** [comment] 2020-06-25 02:23
@MohitShridhar, the process gets killed somewhere in the middle of the full dataset extraction process, not for the other two lighter versions. 

For the training I guess it does the preprocessing for all the splits correctly and gets killed as soon it wants to enter the actual training phase. 

I'll reduce the number of threads to 1, repeat the process using the latest commit and share the results with you here.

**Comment by MohitShridhar** [comment] 2020-06-25 02:27
Ah I see. It looks like for the extraction process, [the 7z bit](https://github.com/askforalfred/alfred/blob/master/data/download_data.sh#L35) is consuming too much RAM.

Ok, let me know about the training. It should be fixed with the latest commit. Thanks!

**Comment by NavidRajabi** [comment] 2020-06-25 02:29
@MohitShridhar, No problem! 

Btw, I've also tried py7zr and the result was the same.

**Comment by MohitShridhar** [comment] 2020-06-25 03:37
I see. Yeah maybe try unzipping it on a different machine with more memory. 

Here is a [zip version](https://drive.google.com/file/d/1xe_asKo6Kb7nQ3c-agPqnhGT7SDJdn84/view?usp=sharing) (~300GB) if it helps. But gDrive is pretty unreliable for large downloads.

**Comment by NavidRajabi** [comment] 2020-06-29 00:06
@MohitShridhar, using the "Trajectory JSONs and Resnet feats (~17GB)" dataset, the training process is still being killed after the preprocess is finished and before the training begins. Also, there is no customizable argument option to reduce the num_threads to 1, if that's the case. Any clue to fix that?

**Comment by NavidRajabi** [comment] 2020-06-29 01:18
@MohitShridhar, btw, I reduced the batch size to 1 and it seems it has accelerated and prevents the process from getting killed so far. I hope this patch works permanently!

**Comment by NavidRajabi** [comment] 2020-06-29 04:05
@MohitShridhar, Unfortunately, the process gets killed after entering the 'valid_seen' phase, even with the batch size of 1!

**Comment by MohitShridhar** [comment] 2020-06-29 05:34
@NavidRajabi can you use a memory profiler (e.g: [stacktrace](https://stackimpact.com/docs/python-profiling/)) to check the memory usage and report back?

**Comment by NavidRajabi** [comment] 2020-06-29 07:00
@MohitShridhar, Actually I cannot run such applications since I am running the experiments on a cluster without sudo access.

**Comment by NavidRajabi** [comment] 2020-06-29 07:18
@MohitShridhar Btw, it seems there is no memory issue:
<img width="725" alt="memory" src="https://user-images.githubusercontent.com/58615241/85984411-26d70180-b9b7-11ea-9eb3-8a74e32270e9.png">

**Comment by MohitShridhar** [comment] 2020-06-29 16:11
@NavidRajabi can you report the output of `dmesg -T| grep -E -i -B100 'killed process'
` based on [this](https://stackoverflow.com/questions/726690/what-killed-my-process-and-why)?

If it's empty, you might need to look into some log files to figure out why the script is being killed. It's hard to say what's happening without the context.

**Comment by NavidRajabi** [comment] 2020-06-29 19:27
@MohitShridhar, Here is the result of the command you mentioned. It seems it goes out of memory and kills the process.

[Mon Jun 29 13:13:28 2020] beegfs: enabling unsafe global rkey
[Mon Jun 29 13:29:34 2020] memory: usage 2097152kB, limit 2097152kB, failcnt 37607
[Mon Jun 29 13:29:34 2020] memory+swap: usage 2097152kB, limit 2097152kB, failcnt 0
[Mon Jun 29 13:29:34 2020] kmem: usage 0kB, limit 9007199254740988kB, failcnt 0
[Mon Jun 29 13:29:34 2020] [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
[Mon Jun 29 13:29:34 2020] [166889] 1224465413 166889    28946      577      13        0             0 bash
[Mon Jun 29 13:29:34 2020] [173531] 1224465413 173531  2311269   552760    1496        0             0 python
[Mon Jun 29 13:29:34 2020] Memory cgroup out of memory: Kill process 175593 (python) score 1057 or sacrifice child
[Mon Jun 29 13:29:34 2020] Killed process 173531 (python), UID 1224465413, total-vm:9245076kB, anon-rss:2086076kB, file-rss:114724kB, shmem-rss:10240kB

**Comment by MohitShridhar** [comment] 2020-06-29 21:38
@NavidRajabi so you _are_ running out of memory. With a batch size of 4, the training script takes 13GB of RAM on my machine. It looks like your cluster has some restrictions on how much memory is allocated to each user. So you would need to talk to your administrator regarding this.

**Comment by NavidRajabi** [comment] 2020-06-30 02:29
@MohitShridhar, Yeah, you're right!
 Thanks for your time and effort!

**Comment by MohitShridhar** [comment] 2020-06-30 17:23
Great! can I close the issue then?

**Comment by NavidRajabi** [comment] 2020-06-30 17:26
@MohitShridhar, Yes, I appreciate your responsiveness!

**Closed** 2020-06-30 18:36 UTC
